### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by janat08** [fiatjaf/cycle-graphql-driver#3]
Subscriptions support isnt described?

**Comment by fiatjaf** [comment]
There's no support.

**Comment by janat08** [comment]
is it difficult to implement api surface, or just no bother?

**Comment by fiatjaf** [comment]
I don't understand what you're saying, but it shouldn't be difficult.

This library is just 20 lines of code, so if you understand how GraphQL subscriptions and Cycle work it should be fairly easy to integrate.

**Comment by janat08** [comment]
Im new to both
